# Generated by Django 3.1.4 on 2021-01-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_auto_20210101_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_light', models.CharField(max_length=200, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('address_option', models.CharField(max_length=50, null=True)),
                ('City', models.CharField(max_length=50, null=True)),
                ('volunteer', models.CharField(max_length=100, null=True)),
                ('hobbies', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
