# Generated by Django 3.1.4 on 2021-01-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_auto_20210101_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
            ],
        ),
    ]
