# Generated by Django 3.1.4 on 2021-01-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0006_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='ProfileImage',
        ),
    ]
