# Generated by Django 3.1.4 on 2021-01-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0008_auto_20210104_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
