# Generated by Django 3.1.4 on 2021-01-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0014_auto_20210105_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='benefits',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='schedule',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
