# Generated by Django 3.1.4 on 2021-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0015_auto_20210105_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
