# Generated by Django 3.1.4 on 2021-01-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0016_employer_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Resume Review', 'resume review'), ('Interview Process', 'Interview Process'), ('Offer Submitted', 'offer submitted'), ('Hired', 'hired')], max_length=100, null=True)),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobApp.candidate')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobApp.employer')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='join',
            field=models.ManyToManyField(to='jobApp.Joiner'),
        ),
    ]
