# Generated by Django 3.1.4 on 2021-01-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0004_addskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
    ]
