# Generated by Django 3.1.4 on 2021-01-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0005_remove_candidate_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
