# Generated by Django 3.1.4 on 2021-01-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0010_candidate_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='addskills',
            name='joiner',
            field=models.ManyToManyField(to='jobApp.Joiner'),
        ),
    ]
