# Generated by Django 3.1.4 on 2021-01-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0013_auto_20210104_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='candidate',
            field=models.ManyToManyField(to='jobApp.Candidate'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='required_skills',
            field=models.TextField(max_length=900, null=True),
        ),
    ]
